"""
Build downloadable HTML or DOCX documents from report/transcript data.

Transcript shape:
  [{"persona": {...}, "respondent_model": str, "turns": [{"turn": int, "question": str, "answer": str}]}]

Report shape (insights / correlation):
  {"title": str, "subtitle": str, "body": str}   (body is markdown-ish plain text)
"""

import io
import re
from datetime import datetime


# ─── HTML ─────────────────────────────────────────────────────────────────────

_HTML_CSS = """
  body { font-family: Georgia, serif; max-width: 860px; margin: 40px auto; padding: 0 32px;
         color: #1a1a2e; line-height: 1.7; background: #fff; }
  h1 { font-size: 1.8rem; color: #1a1a2e; margin-bottom: 4px; }
  h2 { font-size: 1.25rem; color: #16213e; margin-top: 2.5rem; margin-bottom: 0.5rem;
       border-bottom: 2px solid #e0e0f0; padding-bottom: 6px; }
  h3 { font-size: 1rem; color: #0f3460; margin-top: 1.8rem; margin-bottom: 0.3rem; }
  .meta { color: #666; font-size: 0.85rem; margin-bottom: 2rem; }
  .persona-card { background: #f4f4ff; border-left: 4px solid #6c63ff; padding: 14px 18px;
                  border-radius: 6px; margin-bottom: 1rem; font-size: 0.9rem; }
  .persona-card strong { color: #3a3a6e; }
  .interview-summary { background: #f0f7ff; border-left: 3px solid #4a90d9; padding: 10px 16px;
                       margin-bottom: 1.5rem; border-radius: 4px; font-size: 0.9rem; color: #2d4a6e;
                       font-style: italic; }
  .turn { margin-bottom: 1.4rem; }
  .q { font-weight: 600; color: #0f3460; margin-bottom: 4px; }
  .q::before { content: "Q: "; color: #6c63ff; }
  .a { color: #2d2d4e; padding-left: 1.2rem; border-left: 3px solid #e0e0f0; }
  .a::before { content: "A: "; font-weight: 600; color: #888; }
  blockquote { border-left: 4px solid #6c63ff; margin: 12px 0; padding: 8px 16px;
               background: #f9f9ff; color: #444; font-style: italic; }
  .interview-divider { border: none; border-top: 2px dashed #ccc; margin: 2.5rem 0; }
  footer { margin-top: 4rem; font-size: 0.75rem; color: #aaa; border-top: 1px solid #eee;
           padding-top: 12px; }
"""


def _md_line_to_html(line: str) -> str:
    """Convert a single markdown-ish line to an HTML snippet."""
    if line.startswith("### "):
        return f"<h3>{line[4:]}</h3>"
    if line.startswith("## ") or line.startswith("# "):
        text = re.sub(r"^#+\s", "", line)
        return f"<h2>{text}</h2>"
    if line.startswith("> "):
        return f"<blockquote>{line[2:]}</blockquote>"
    if line.startswith("- ") or line.startswith("* "):
        return f"<li>{line[2:]}</li>"
    if re.match(r"^\d+\.\s", line):
        return f"<p><strong>{line}</strong></p>"
    # inline bold **text**
    line = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)
    return f"<p>{line}</p>" if line.strip() else "<br>"


def _body_to_html(text: str) -> str:
    lines = text.split("\n")
    chunks, in_list = [], False
    for line in lines:
        is_li = line.startswith("- ") or line.startswith("* ")
        if is_li and not in_list:
            chunks.append("<ul>")
            in_list = True
        elif not is_li and in_list:
            chunks.append("</ul>")
            in_list = False
        chunks.append(_md_line_to_html(line))
    if in_list:
        chunks.append("</ul>")
    return "\n".join(chunks)


def build_report_html(title: str, subtitle: str, body: str) -> bytes:
    generated = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <style>{_HTML_CSS}</style>
</head>
<body>
  <h1>{title}</h1>
  <p class="meta">{subtitle} &nbsp;|&nbsp; Generated {generated}</p>
  {_body_to_html(body)}
  <footer>Generated by Interstellar Surveys</footer>
</body>
</html>"""
    return html.encode("utf-8")


def build_transcripts_html(project_name: str, interviews: list) -> bytes:
    generated = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    body_parts = []

    for idx, iv in enumerate(interviews):
        persona = iv.get("persona", {})
        name = persona.get("name", f"Participant {idx + 1}")

        _LABELS = {
            "age": "Age", "gender": "Gender", "occupation": "Occupation",
            "role": "Role", "department": "Department", "industry": "Industry",
            "years_experience": "Experience", "country": "Country",
            "education": "Education", "region": "Region",
        }
        attrs = []
        for key in ("age", "gender", "occupation", "role", "department",
                    "industry", "years_experience", "country", "education", "region"):
            val = persona.get(key)
            if val:
                label = _LABELS.get(key, key.title())
                suffix = " yrs" if key == "years_experience" else ""
                attrs.append(f"<strong>{label}:</strong> {val}{suffix}")
        background = persona.get("background", "")
        summary = iv.get("summary", "")

        body_parts.append(f"""
<h2>Interview {idx + 1}: {name}</h2>
<div class="persona-card">
  {"&ensp;|&ensp;".join(attrs)}<br>
  {f"<em>{background}</em>" if background else ""}
</div>
{f'<div class="interview-summary">{summary}</div>' if summary else ""}""")

        for turn in iv.get("turns", []):
            q = turn.get("question", "").strip()
            a = turn.get("answer", "").strip()
            body_parts.append(f"""
<div class="turn">
  <p class="q">{q}</p>
  <p class="a">{a}</p>
</div>""")

        if idx < len(interviews) - 1:
            body_parts.append('<hr class="interview-divider">')

    body_html = "\n".join(body_parts)
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Interview Transcripts — {project_name}</title>
  <style>{_HTML_CSS}</style>
</head>
<body>
  <h1>Interview Transcripts</h1>
  <p class="meta">Project: <strong>{project_name}</strong> &nbsp;|&nbsp;
     {len(interviews)} interviews &nbsp;|&nbsp; Generated {generated}</p>
  {body_html}
  <footer>Generated by Interstellar Surveys</footer>
</body>
</html>"""
    return html.encode("utf-8")


# ─── DOCX ─────────────────────────────────────────────────────────────────────

def _apply_docx_styles(doc):
    from docx.shared import Pt, RGBColor
    from docx.oxml.ns import qn
    import docx

    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    for heading_name, size, bold in [("Heading 1", 18, True), ("Heading 2", 14, True), ("Heading 3", 12, True)]:
        h = doc.styles[heading_name]
        h.font.name = "Calibri"
        h.font.size = Pt(size)
        h.font.bold = bold
        h.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)


def _parse_body_to_docx(doc, text: str):
    from docx.shared import Pt, RGBColor

    for line in text.split("\n"):
        stripped = line.strip()
        if not stripped:
            doc.add_paragraph()
            continue
        if stripped.startswith("### "):
            doc.add_heading(stripped[4:], level=3)
        elif stripped.startswith("## ") or stripped.startswith("# "):
            doc.add_heading(re.sub(r"^#+\s", "", stripped), level=2)
        elif stripped.startswith("> "):
            p = doc.add_paragraph(stripped[2:])
            p.style = "Intense Quote" if "Intense Quote" in [s.name for s in doc.styles] else doc.styles["Normal"]
        elif stripped.startswith("- ") or stripped.startswith("* "):
            doc.add_paragraph(stripped[2:], style="List Bullet")
        elif re.match(r"^\d+\.\s", stripped):
            p = doc.add_paragraph(stripped, style="List Number")
        else:
            cleaned = re.sub(r"\*\*(.+?)\*\*", r"\1", stripped)
            p = doc.add_paragraph()
            run = p.add_run(cleaned)
            if re.search(r"\*\*", line):
                run.bold = True


def build_report_docx(title: str, subtitle: str, body: str) -> bytes:
    import docx
    from docx.shared import Pt

    doc = docx.Document()
    _apply_docx_styles(doc)

    doc.add_heading(title, level=1)
    meta = doc.add_paragraph(f"{subtitle}  |  Generated {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    meta.runs[0].font.size = Pt(9)
    meta.runs[0].font.color.rgb = __import__("docx").shared.RGBColor(0x88, 0x88, 0x88)
    doc.add_paragraph()

    _parse_body_to_docx(doc, body)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def build_transcripts_docx(project_name: str, interviews: list) -> bytes:
    import docx
    from docx.shared import Pt, RGBColor

    doc = docx.Document()
    _apply_docx_styles(doc)

    doc.add_heading("Interview Transcripts", level=1)
    meta = doc.add_paragraph(
        f"Project: {project_name}  |  {len(interviews)} interviews  |  "
        f"Generated {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"
    )
    meta.runs[0].font.size = Pt(9)
    meta.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    for idx, iv in enumerate(interviews):
        doc.add_paragraph()
        persona = iv.get("persona", {})
        name = persona.get("name", f"Participant {idx + 1}")

        doc.add_heading(f"Interview {idx + 1}: {name}", level=2)

        _LABELS = {
            "age": "Age", "gender": "Gender", "occupation": "Occupation",
            "role": "Role", "department": "Department", "industry": "Industry",
            "years_experience": "Experience", "country": "Country",
            "education": "Education", "region": "Region",
        }
        attrs = []
        for k in ("age", "gender", "occupation", "role", "department",
                  "industry", "years_experience", "country", "education", "region"):
            val = persona.get(k)
            if val:
                suffix = " yrs" if k == "years_experience" else ""
                attrs.append(f"{_LABELS.get(k, k.title())}: {val}{suffix}")
        if persona.get("background"):
            attrs.append(persona["background"])
        card = doc.add_paragraph("  |  ".join(attrs))
        card.runs[0].font.size = Pt(9)
        card.runs[0].italic = True

        summary = iv.get("summary", "")
        if summary:
            p_sum = doc.add_paragraph(summary)
            p_sum.runs[0].italic = True
            p_sum.runs[0].font.size = Pt(10)
            p_sum.runs[0].font.color.rgb = RGBColor(0x2d, 0x4a, 0x6e)

        for turn in iv.get("turns", []):
            q = turn.get("question", "").strip()
            a = turn.get("answer", "").strip()
            p_q = doc.add_paragraph()
            p_q.add_run("Q: ").bold = True
            p_q.add_run(q)
            p_a = doc.add_paragraph()
            p_a.add_run("A: ").bold = True
            p_a.add_run(a)
            p_a.runs[0].font.color.rgb = RGBColor(0x44, 0x44, 0x44)

        if idx < len(interviews) - 1:
            doc.add_paragraph("─" * 60)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
